include:
  # nRFMicro (форм-фактор Pro Micro, nRF52840)
  - board: nrfmicro_13
    shield: corne_left
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    snippet: studio-rpc-usb-uart
  - board: nrfmicro_13
    shield: corne_right

  # nice!nano v2
  - board: nice_nano_v2
    shield: corne_left
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: corne_right

  # Seeed XIAO BLE
  - board: seeeduino_xiao_ble
    shield: corne_left
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: corne_right
